In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# Инициализация CountVectorizer
count = CountVectorizer()

# Массив документов
docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining, the weather is sweet, and one and one is two'
])

# Создание мешка слов
bag = count.fit_transform(docs)

# Вывод результата (опционально)
print(bag.toarray())
print(count.get_feature_names_out())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]
['and' 'is' 'one' 'shining' 'sun' 'sweet' 'the' 'two' 'weather']


In [2]:
count.vocabulary_

{'the': 6,
 'sun': 4,
 'is': 1,
 'shining': 3,
 'weather': 8,
 'sweet': 5,
 'and': 0,
 'one': 2,
 'two': 7}

In [3]:
import re

In [7]:
[re.sub(r'\W+', ' ', i) for i in docs]

['The sun is shining',
 'The weather is sweet',
 'The sun is shining the weather is sweet and one and one is two']

In [19]:
[re.findall("weather", i) for i in docs]

[[], ['weather'], ['weather']]

In [20]:
str = 'an example word:cat!!'
match = re.search(r'word:\w\w\w', str)
# If-statement after search() tests if it succeeded
if match:
  print('found', match.group()) ## 'found word:cat'
else:
  print('did not find')

found word:cat
