In [1]:
import scipy
import numpy as np
import pandas as pd


In [2]:
A = np.array([ [1,-1], [-2,2] ]) 
B = np.array([ [1,-1], [-2,3] ])

print( scipy.linalg.null_space(A) ) 
print( scipy.linalg.null_space(B) )

[[0.70710678]
 [0.70710678]]
[]


In [28]:
# create the matrix 
m = 4
n = 4
A = np.random.randn(m,n)

# initialize
Q = np.zeros((m,n))


# the GS algo
for i in range(n):
    
    # initialize
    Q[:,i] = A[:,i]
    
    # orthogonalize
    a = A[:,i] # convenience
    for j in range(i): # only to earlier cols
        q = Q[:,j] # convenience
        Q[:,i]=Q[:,i]-np.dot(a,q)/np.dot(q,q)*q
    
    # normalize
    Q[:,i] = Q[:,i] / np.linalg.norm(Q[:,i])

    
# "real" QR decomposition for comparison
Q2,R = np.linalg.qr(A)


# note the possible sign differences.
# seemingly non-zero columns will be 0 when adding
print( np.round( Q-Q2 ,10) ), print(' ')
print( np.round( Q+Q2 ,10) )

[[ 0.10111456  0.          0.79213454 -0.95426155]
 [-0.05316238 -0.          0.98952546 -1.21754129]
 [-1.75563924 -0.         -0.72480418 -0.61779326]
 [ 0.95114692  0.         -1.3667557  -1.10693703]]
 
[[ 0.          1.5657853   0.         -0.        ]
 [-0.         -1.23919584 -0.         -0.        ]
 [-0.          0.10354342 -0.          0.        ]
 [ 0.         -0.04459606 -0.          0.        ]]


In [9]:
A = np.array([
    [-0.535, 0.707], 
    [-0.267, -0.707], 
    [0.802, 0]
])
A.T@A

array([[ 1.000718, -0.189476],
       [-0.189476,  0.999698]])