In [2]:
import torch
import numpy as np

Задание 1.

Посмотрите на представленный ниже код и ответьте на вопрос.

Какой объект хранится в переменной d?

In [3]:
a = np.arange (1., 5.)
b = np.arange (1., 4.)
d = np.zeros ((4,3))
for i in range (4) :
    for j in range (3):
        d[i,j] += a[i] * b[j]

In [7]:
d, a, b

(array([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.]]),
 array([1., 2., 3., 4.]),
 array([1., 2., 3.]))

Выберите один ответ:

матрица, полученная в результате векторного произведения (*)

матрица, полученная в результате матричного перемножения

тензор, полученный в результате тензорного произведения

тензор, полученный в результате векторного произведения

матрица, полученная в результате поэлементного перемножения

---
Задание 2.

Какой из перечисленных вариантов решает ту же задачу, что и представленный ниже код?

In [8]:
a = np.arange (1., 5.)
b = np.arange (1., 4.)
d = np.zeros ((4,3))
for i in range (4):
    for j in range (3):
        d[i,j] += a[i] * b[j]
        
d

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.]])

In [12]:
np.tensordot(a, b, axes=0)

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.]])

---
Задание 3.

Что будет выведено на экран в результате выполнения представленного ниже кода?

In [19]:
t1 = torch.randn(size=(2, 3, 4, 9))
t2 = t1.view(6, -1, 3)
print (t2.size()[1])

12


In [21]:
initial_x = torch.Tensor([15])
tensor = torch.nn.Parameter(initial_x, requires_grad=True)

In [23]:
initial_x = torch.Tensor([15.])
tensor = torch.nn.Parameter(initial_x, requires_grad=True)

In [24]:
tensor = torch.tensor([15.], requires_grad=True)

In [25]:
tensor = torch.tensor([15], requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [28]:
def lesson_func_tensor(x):
    return (torch.sin(x/5) * torch.exp(x/10)) + (5 * torch.exp(-x/5))

In [29]:
x = torch.tensor([15.], requires_grad=True)
optimizer = torch.optim.SGD([x], lr=0.3)

for _ in range(45):
    optimizer.zero_grad()
    loss = lesson_func_tensor(x)
    loss.backward()
    optimizer.step()

print(f"Final x: {x.item():.4f}")  # Результат: ~25.1503

Final x: 25.8549


In [32]:
a = np.arange (1., 5.)
b = np.arange (1., 4.)
d = np.zeros ((4,3))
for i in range (4):
    for j in range (3):
        d[i,j] += a[i] * b[j]
        
d

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.]])

In [39]:
torch.tensordot(torch.Tensor(a), torch.Tensor(b), dims=0)

tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.]])

In [40]:
np.tensordot(a, b, axes=0)

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.]])