In [1]:
from sklearn.metrics import mean_squared_error
import numpy as np

Задание 27
1 point possible (graded)

Даны истинные ответы _true = [1.23, 2.35, 2.75] и предсказания У_pred = [1.01, 12.3, 2.74] регрессионной модели машинного
обучения.
Рассчитайте метрику RMSE. Ответ округлите до двух знаков после точки-разделителя.

In [2]:
y_true = [1.23, 2.35, 2.75]
У_pred = [1.01, 12.3, 2.74]

print(np.sqrt(mean_squared_error(y_true, У_pred)).round(2))

5.75


In [3]:
test = 1

___

In [3]:
A = np.array([[4, 7], [5, 10]])
A_inv = np.linalg.inv(A)

b = np.array([20,30])
A_inv@b


array([-2.,  4.])

---

In [4]:
w_ = np.array([1, 1])
A = np.array([[1, -5], [2, 1], [1, 1]])
b = np.array([1, 2, 2])


In [5]:
b_ = A @ w_
b_

array([-4,  3,  2])

In [6]:
e = b - b_
e

array([ 5, -1,  0])

----

In [7]:
A = np.array([[1, 2], [-3, 1], [1, 2], [1, -1]])
b = np.array([1, 4, 5, 0])
G = A.T @ A
G

array([[12,  0],
       [ 0, 10]])

In [8]:
G_inv = np.linalg.inv(G)
G_inv

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [9]:
Atb = A.T @ b
Atb

array([-6, 16])

In [10]:
w_ = G_inv @ Atb
w_

array([-0.5,  1.6])

---

Задание 4.3

Стандартизируйте вектор x = (12, 8)T - , приведя его к единичной длине. В качестве ответа введите координаты полученного вектора. 

Ответ округлите до третьего знака после точки-разделителя.

In [11]:
x = np.array((12, 8)).T
x_cent = x - x.mean()
x_cent

array([ 2., -2.])

In [12]:
x_st = x_cent/np.linalg.norm(x_cent)
x_st.round(3)

array([ 0.707, -0.707])

---

Задание 4.7

Вычислите коэффициент корреляции между векторами © = (5, 1, 2) ° и it = (1, 2,8) Г.
Ответ округлите до двух знаков после точки-разделителя.

In [13]:
v = np.array((5, 1, 2)).T
u = np.array((4, 2, 8)).T
np.corrcoef(v, u)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

---

Задание 4.8

Составьте корреляционную матрицу для системы векторов:

x_1 = (5.1, 1.8, 2.1, 10.3, 12.1, 12.6).T
x_2 = (10.2, 3.7, 4.1, 20.5, 24.2, 24.1).T
x_3 = (2.5, 0.9, 1.1, 5.1, 6.1, 6.3).T

Для расчёта используйте библиотеку NumPy или Pandas.

In [14]:
x_1 = np.array((5.1, 1.8, 2.1, 10.3, 12.1, 12.6)).T
x_2 = np.array((10.2, 3.7, 4.1, 20.5, 24.2, 24.1)).T
x_3 = np.array((2.5, 0.9, 1.1, 5.1, 6.1, 6.3)).T

In [15]:
corr_mat = np.corrcoef((x_1, x_2, x_3))
corr_mat


array([[1.        , 0.99925473, 0.99983661],
       [0.99925473, 1.        , 0.99906626],
       [0.99983661, 0.99906626, 1.        ]])

In [16]:
np.linalg.matrix_rank(corr_mat)


3

In [17]:
np.linalg.det(corr_mat).round(7)

5e-07

---

In [18]:
y = np.array([3, 7, -5, 21])
A = np.array(
    [[1, 1, 1, 1],
    [1, 3, -2, 9],
    [1, 9, 4, 81]]).T

w_hat = np.linalg.inv(A.T @ A) @ A.T @ y
w_hat.round(1)


array([ 0.1,  2.5, -0. ])

---

In [19]:
A = np.array([
    [1, 1, 1, 1, 1],
    [5, 9, 4, 3, 5],
    [15, 18, 18,19, 19],
    [7, 6, 7, 7, 7]
]).T

alpha = 1
E = np.eye(4)

y =np.array([24, 22, 35, 33, 36])

w_hat = np.linalg.inv((A.T @ A + alpha*E)) @ A.T @ y
w_hat.round(2)

array([-0.09, -1.71,  1.91,  0.73])

---

In [20]:
F = np.array([[2,1],[1,2]]).T
u = np.array([1,-1])
F@u

array([ 1, -1])

In [21]:
A = np.array([[5, 1], [1, 5]])
np.linalg.eig(A)

(array([6., 4.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

___


In [22]:
A = np.array([[1, 3, 5], [4, -4, 9], [13, 7, 12]])
np.linalg.eig(A)

(array([19.52189628, -3.75422737, -6.76766891]),
 array([[-0.29813912, -0.73141292,  0.25078429],
        [-0.38491044,  0.59044076, -0.95097448],
        [-0.87347411,  0.34119621,  0.18098281]]))

In [23]:
A = np.array([[1, 9, 4], [9, 4, 7], [4, 7, 12]])
G = A.T @ A
np.linalg.eig(G)

(array([391.37004987,  45.77088847,  15.85906166]),
 array([[-0.41955589, -0.7323045 , -0.5363795 ],
        [-0.55709648,  0.67425896, -0.48478693],
        [-0.71667034, -0.09541992,  0.69085358]]))

---

In [24]:
x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([
[1, 0.9922],
[0.9922, 1],
])

eig_values, eig_vectors = np.linalg.eig(C)

print(eig_values, eig_vectors)

[1.9922 0.0078] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [25]:
x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

[-0.24  0.86 -0.29 -0.33]


---

In [26]:
A = {
    'bennet@xyz.com',
    'darcy@abc.com',
    'margaret@xyz.com',
    'pa@hhh.com',
    'marimari@xyz.com',
    'mallika@yahoo.com',
    'abc@xyz.com',
    '0071235@gmail.ru'
}

B ={
    'marimari@xyz.com',
    'darcy@abc.com',
    '0071235@gmail.ru',
    'darcy@abc.com',
    'petr44@xyz.com',
    'katrin@ya.com'
}


In [27]:
len(A.intersection(B))

3

In [28]:
len(A.symmetric_difference(B))

7