In [165]:
import numpy as np

In [166]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [167]:
A

array([[10, 10,  6],
       [ 5, 10,  9],
       [10, 10,  7]])

In [168]:
B

array([[ 3,  3, -2],
       [-1, -2,  0],
       [ 3,  0, -1]])

In [169]:
# Поэлементное умножение
A*B

array([[ 30,  30, -12],
       [ -5, -20,   0],
       [ 30,   0,  -7]])

In [170]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 38  10 -26]
 [ 32  -5 -19]
 [ 41  10 -27]]


In [171]:
# Матричное умножение
np.dot(A,B)

array([[ 38,  10, -26],
       [ 32,  -5, -19],
       [ 41,  10, -27]])

In [172]:
# Матричное умножение
A@B

array([[ 38,  10, -26],
       [ 32,  -5, -19],
       [ 41,  10, -27]])

In [173]:
# Порядок умножения AB != BA
B@A

array([[ 25,  40,  31],
       [-20, -30, -24],
       [ 20,  20,  11]])

In [174]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[10  7  8 11  7]
 [11 10 11  8  8]
 [ 9 11 10 11  7]]
B:
 [[ 1  0]
 [-2 -1]
 [-2 -1]
 [ 0 -2]
 [-2  1]]


In [175]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-34, -30],
       [-47, -29],
       [-47, -36]])

In [176]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 1 -4 -2  0]
 [-3 -2 -4  1]
 [-3 -2 -4  3]
 [ 2 -4 -1  1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 1 -8  0  0]
 [-3 -4  0 -1]
 [-3 -4  0 -3]
 [ 2 -8  0 -1]]
DA:
 [[ 1 -4 -2  0]
 [-6 -4 -8  2]
 [ 0  0  0  0]
 [-2  4  1 -1]]


In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [ ]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

In [ ]:
A = np.array([[5, -1, 3, 1, 2], [-2, 8, 5, -1, 1]])
x = np.array([1, 2, 3, 4, 5])


In [ ]:
A@x

array([26, 30])

---

Задание 7.2
1 point possible (graded)

Даны две матрицы
Найдите произведение матриц А и В в том порядке, в котором их можно умножить.
В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [ ]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [ ]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

---

Задание 7.3
1 point possible (graded)

Дана система векторов
Составьте матрицу А, расположив векторы х, ч, ~ в строках. Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы А)
системы векторов Х, Ч, Z.
Чему равна полученная матрица Грама G?

In [ ]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [ ]:
A = np.array([x,y,z]).T
A

array([[ 1,  2, -1],
       [ 2,  1,  1],
       [ 1, -1, -1],
       [ 0,  1,  0],
       [ 4,  0,  0]])

In [ ]:
G = A @ A.T
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

---

УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и
Юра.

Вам предоставлены две таблицы (DataFrame): Count DF И Price DF.

• B DataFrame Count DF содержится информация по количеству услуг, оказанных каждым стилистом за
апрель.

B DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах
рублей.

In [ ]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7],
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0],
    'Окрашивания': [12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка': [15, 25, 30, 14, 25, 17, 25, 31],
    'Уход': [10, 6, 4, 5, 18, 12, 20, 28]
},
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5],
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4],
    'Окрашивания': [1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка': [0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход': [1, 1, 2, 2, 1.5, 2.5, 1.7, 2]
},
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра']
)


Задание 7.4
1 point possible (graded)

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий: com = np.array ([0.2, 0.2, 0.3, 0.1, 0.1])

Выберите координаты вектора прибыли салона:

In [ ]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
rev = Count_DF * Price_DF
rev_cut = rev * com
rev_cut['sum_salon'] = rev_cut[rev.columns.to_list()].sum(axis=1)
rev_cut['sum_salon'].values

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

---

Задание 7.5
1 point possible (graded)

Найдите вектор прибыли стилистов.
Выберите координаты полученного вектора:

In [ ]:
rev['sum'] = rev[rev.columns.to_list()].sum(axis=1)

In [ ]:
rev['stylist'] = rev['sum'] - rev_cut['sum_salon']

In [ ]:
rev

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход    sum  \
Аня               20.0              7.5         12.0     12.0  10.0   61.5   
Борис              3.6             52.5          3.0     25.0   6.0   90.1   
Вика              24.0             24.0          0.0     15.0   8.0   71.0   
Галя               7.2              9.6         50.4     11.2  10.0   88.4   
Дима              15.0             87.5         54.0     25.0  27.0  208.5   
Егор              50.0             15.0          6.0     34.0  30.0  135.0   
Женя              24.2              1.0          6.0     12.5  34.0   77.7   
Юра               31.5              0.0         77.5     31.0  56.0  196.0   

       stylist  
Аня      50.20  
Борис    74.88  
Вика     59.10  
Галя     67.80  
Дима    166.60  
Егор    113.80  
Женя     66.21  
Юра     157.75

---

In [178]:
A = np.array(([1, 2], [1, 1]))
B = np.array(([5, -2], [-1, 4]))



In [181]:
np.linalg.det(A)

-1.0

In [182]:
np.linalg.det(B)

17.999999999999996

In [183]:
np.linalg.det(A+B)

29.99999999999999

---

Задание 10.1

Дана матрица А:

A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

Найдите матрицу, обратную матрице А.

•В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [185]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [188]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [192]:
A_inv[1][0].round(3)

0.375

____

In [194]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np. array([3, -4, 3, -1, -4])


Задание 10.2

Найдите ранг системы векторов v1, v2, v3, v4. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [195]:
A = np.array([v1, v2, v3, v4]).T
A 

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [196]:
np.linalg.matrix_rank(A)

4

---



Задание 10.4


Найдите матрицу Грама системы векторов векторов v1, v2, v3, v4: G = A.T @ A. 

В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [201]:
G = A.T @ A
G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

---

Задание 10 5

Найдите определитель матрицы Грама G системы v1, v2, v3, v4. Ответ округлите до целого числа.

In [203]:
np.linalg.det(G).round(3)

3716648.0

---

asdЗадание 10.7

Найдите обратную матрицу к матрице Грама G системы v1, v2, v3, v4. В качестве ответа запишите элемент из первого столбца третьей строки,
округлив его до трёх знаков после точки-разделителя.

In [205]:
G_inv = np.linalg.inv(G).round(3)
G_inv

array([[ 0.017, -0.028, -0.026,  0.016],
       [-0.028,  0.072,  0.03 , -0.027],
       [-0.026,  0.03 ,  0.077, -0.026],
       [ 0.016, -0.027, -0.026,  0.035]])