In [3]:
import numpy as np

In [4]:
array = np.arange(10) ** 4
array_2 = np.arange(10) ** 3

In [8]:
print(array, array_2)

[   0    1   16   81  256  625 1296 2401 4096 6561] [  0   1   8  27  64 125 216 343 512 729]


In [12]:
array_sum = np.sum(np.add(array, array_2))
array_sum

17358

In [13]:
array_difference = np.subtract(np.sum(array), np.sum(array_2))
array_difference

13308

In [14]:
game_payments2 = array[1]
game_payments2

1

In [15]:
some_data =  [
    [3, 8, 1, 0, 1, 2],
    [9, 2, 7, 3, 0, 4],
    [2, 5, 1, 3, 1, 8],
    [5, 1, 2, 1, 1, 0]
]
some_data = np.array(some_data)

In [16]:
lines = some_data[1:]
lines

array([[9, 2, 7, 3, 0, 4],
       [2, 5, 1, 3, 1, 8],
       [5, 1, 2, 1, 1, 0]])

In [17]:
last_column = some_data[:,-1]
last_column

array([2, 4, 8, 0])

In [18]:
array_t = some_data.T
array_t

array([[3, 9, 2, 5],
       [8, 2, 5, 1],
       [1, 7, 1, 2],
       [0, 3, 3, 1],
       [1, 0, 1, 1],
       [2, 4, 8, 0]])

In [19]:
array_sum = some_data.sum()
array_sum

70

In [20]:
array_avg = some_data.mean()
array_avg

2.9166666666666665

In [22]:
A = np.array([[3, 2, 1], [1, 6, 2], [4, 1, 5]])
B = np.array([360, 300, 675])

np.linalg.solve(A, B)


array([90., 15., 60.])

In [23]:
np.linalg.lstsq(A, B)

/var/folders/df/dz8wtw0j7791hg98mrx_thxc0000gn/T/ipykernel_10330/1844739126.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([90., 15., 60.]),
 array([], dtype=float64),
 3,
 array([8.51969208, 4.64157985, 1.69427958]))

In [3]:
import statsmodels as st
import random
import scipy.stats as st
import numpy as np


In [4]:
random.seed(10)
ages = []
for i in range(0, 30):
    n = random.randint(18, 75)
    ages.append(n)

In [6]:
confidence_level = 0.99
mean_age = np.mean(ages)
std_error = st.sem(ages)
df = len(ages) - 1

confidence_interval = st.t.interval(confidence_level, df, loc=mean_age, scale=std_error)
print(confidence_interval)

(35.61675553211002, 52.18324446788998)
