In [1]:
import numpy as np
import torch

In [7]:
tensor_test = torch.tensor([[0.1921, 0.0000, 0.0000],
                            [0.2041, 0.1659, 0.0000],
                            [0.2036, 0.1659, 0.1662],
                            [0.1869, 0.1667, 0.1668],
                            [0.1830, 0.1669, 0.1670],
                            [0.1935, 0.1663, 0.1666]])

In [8]:
tensor_test.shape

torch.Size([6, 3])

In [2]:
import pandas as pd

data = {
    "player_number": [10, 8, 12, 22, 36, 7, 1, 20, 9, 4, 14],
    "height": [168, 176, 178, 191, 185, 183, 185, 179, 169, 183, 167],
    "weight": [76, 77, 79, 81, 82, 79, 74, 84, 73, 71, 68],
    "score": [95, 86, 94, 96, 95, 95, 89, 83, 99, 78, 82],
}

df = pd.DataFrame(data)

def solution(A): # A - некий датафрейм
    x = A.query("score > 90")
    x = x["weight"].mean().round(5)# ... ваш код
    return x

print(solution(df))

78.33333


In [3]:
import numpy as np
from scipy import stats

# ваш код
data = stats.norm(50, 2)
CDF = data.cdf(46).round(5)

print(CDF)

0.02275


In [4]:
from scipy import stats 

# Создаем данные с нормальным распределением, где среднее = 0 и стандартное отклонение = 1 (Z распределение)
data = stats.norm(0,1) 

# PPF - "...определяет значение, которое случайная величина не превысит с вероятностью а%..."
Z = data.ppf(0.05) # c вероятностью 5% случайная величина не превысит -1.644 


s = 5.34 # стандартное отклонение
h_05 = 48.5 # 0.05 персентиль


# Z = ( x - x_mean ) / s - формула Z - преобразования. Требуется найти x_mean, а все остальное известно.
# По сути делаем обратное Z - преобразование с нахождением x_mean
x_mean = - (Z * s - h_05)
x_mean

57.28351836792086

In [39]:
import numpy as np
nums = np.array([2,7,11,15])
target = 9

In [40]:
temp_list = target - nums
# temp_target
temp_list

array([ 7,  2, -2, -6])

In [41]:
[i if i > 0 else 0 for i in temp_list]

[7, 2, 0, 0]

In [42]:
def twoSum(nums, target):
    seen = {} 
    
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i

In [44]:
twoSum(nums, target)

[0, 1]

In [7]:
class User:
    def __init__(self, username, email):
        self.username = username
        self.email = email
    
    def __str__(self):
        # "Человекочитаемое" представление
        return f"Пользователь {self.username}"

    def __repr__(self):
        # "Однозначное" представление для разработчика
        # Обратите внимание на !r после имен атрибутов
        return f"User(username={self.username}, email={self.email!r})"

In [6]:
# Создаем пользователя
user_alex = User("Alex", "alex@example.com")

# 1. print() использует __str__ (если он есть)
print("--- Вывод print() ---")
print(user_alex)

# 2. repr() всегда использует __repr__
print("\n--- Вывод repr() ---")
print(repr(user_alex))

# 3. Печать контейнера использует __repr__ для своих элементов
print("\n--- Вывод списка с объектом ---")
users_list = [user_alex]
print(users_list)

--- Вывод print() ---
Пользователь Alex

--- Вывод repr() ---
User(username='Alex', email='alex@example.com')

--- Вывод списка с объектом ---
[User(username='Alex', email='alex@example.com')]


In [8]:
# Создаем пользователя
user_alex = User("Alex", "alex@example.com")

# 1. print() использует __str__ (если он есть)
print("--- Вывод print() ---")
print(user_alex)

# 2. repr() всегда использует __repr__
print("\n--- Вывод repr() ---")
print(repr(user_alex))

# 3. Печать контейнера использует __repr__ для своих элементов
print("\n--- Вывод списка с объектом ---")
users_list = [user_alex]
print(users_list)

--- Вывод print() ---
Пользователь Alex

--- Вывод repr() ---
User(username=Alex, email='alex@example.com')

--- Вывод списка с объектом ---
[User(username=Alex, email='alex@example.com')]


In [2]:
class User:
    def __init__(self, age):
        self._age = age

    # 1. Применяем декоратор @property к нашему геттеру
    @property
    # 2. Переименовываем метод в то имя, которое мы хотим видеть снаружи
    def age(self):
        """Это метод-геттер, замаскированный под атрибут."""
        print("(Вызывается геттер)") # Добавим для наглядности
        return self._age

user = User(30)

# Теперь, чтобы получить возраст, мы ОБРАЩАЕМСЯ К АТРИБУТУ
# Скобки () больше не нужны!
print(user.age)

(Вызывается геттер)
30


In [2]:
#   Вершина ромба
#       (A)
class PoweredDevice:
    def turn_on(self):
        print("PoweredDevice: Включено.")

#   Два потомка от A
#  (B)           (C)
class Scanner(PoweredDevice):
    def turn_on(self):
        super().turn_on() # Вызываем родителя
        print("Scanner: Готов к сканированию.")

class Printer(PoweredDevice):
    def turn_on(self):
        super().turn_on() # Вызываем родителя
        print("Printer: Готов к печати.")

#   Низ ромба: потомок от B и C
#       (D)
class MFD(Scanner, Printer): # МФУ (Многофункциональное устройство)
    def turn_on(self):
        super().turn_on()
        print("MFD: Готово к работе.")

In [3]:
test = MFD()
test.turn_on()

PoweredDevice: Включено.
Printer: Готов к печати.
Scanner: Готов к сканированию.
MFD: Готово к работе.


In [43]:
class DictMixin:
    def to_dict(self):
        return {k:v for k, v in self.__dict__.items() if not k.startswith("_")}
    
class User:
    def __init__(self, name, email):
        self.name = name
        self.email = email
        self._password_hash = 0
        
class SerializableUser(User, DictMixin):
    pass

In [44]:
SerializableUser("josh", 12).to_dict()

{'name': 'josh', 'email': 12}

In [13]:
test = [("apple", 100), ("peach", 200), ("apple", 100)]
test

[('apple', 100), ('peach', 200), ('apple', 100)]

In [ ]:
from collections import Counter
{k:v for k,v in test}

SyntaxError: invalid syntax (65022437.py, line 2)

In [32]:
test_2 = dict(Counter(test))
test_2

{('apple', 100): 2, ('peach', 200): 1}

In [22]:
test_2.values()

dict_values([2, 1])

In [52]:
import numpy as np

In [53]:
price = np.array([float(v) for k, v in test_2])
price

array([100., 200.])

In [54]:
value = np.array([i for i in test_2.values()])
value

array([2, 1])

In [56]:
float(price @ value)

400.0

In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns