1. Используя библиотеку numpy, решите систему линейных уравнений:

2x+y−z=8,

−3x−y+2z=−11,

−2x+y+2z=−3

In [11]:
import numpy as np

# Создаем матрицу коэффициентов
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Создаем вектор значений
B = np.array([8, -11, -3])

# Решаем систему уравнений через транспонирование
X = np.linalg.inv(A.T @ A) @ A.T @ B
# Либо по простому
# X = np.linalg.solve(A, B)

print("Решение: x =", X[0], ", y =", X[1], ", z =", X[2])


Решение: x = 1.9999999999996803 , y = 3.000000000000128 , z = -1.00000000000027


2. Решите квадратное уравнение(найдите его корни): $2x^2+4x−6=0$.
Используйте для этой задачи библиотеку math.

Для отработки материала, решение должно быть представлено через нахождение дискриминанта по формуле: $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$

In [12]:
import math

# Коэффициенты квадратного уравнения
a = 2
b = 4
c = -6

# Вычисление дискриминанта
discriminant = math.pow(b, 2) - 4 * a * c

# Вычисление корней уравнения
if discriminant >= 0:
    x1 = (-b + math.sqrt(discriminant)) / 2 * a
    x2 = (-b - math.sqrt(discriminant)) / 2 * a
    print("Корни уравнения:", x1, x2)
else:
    print("Корни не являются вещественными числами")

Корни уравнения: 4.0 -12.0


3. Вычислите синус угла $𝜋\over3$ с использованием первых четырех членов ряда Тейлора.
Серия Тейлора для синуса: $$x = x - {x^3\over3!} + {x^5\over5!} - {x^7\over7!} + ...$$
Использойте библиотеку math

In [34]:
import math

# Угол в радианах
x = math.pi / 3

# Вычисление синуса методом ряда Тейлора
sin_approximation = (
    x - x**3 / math.factorial(3) + x**5 \
        / math.factorial(5) - x**7 / math.factorial(7)
)

print("Приближенное значение синуса методом Тейлора:",\
    round(sin_approximation, 2))

Приближенное значение синуса методом Тейлора: 0.87


4. Найдите площадь треугольника, если его стороны $a = 7, b = 8$, а угол между ними $С=45^o$
Подсказка: нужно найти площадь треугольника через синус угла по формуле:
$$A= {1\over2}a*b*sin(C)$$

In [14]:
import math

# Стороны треугольника и угол в градусах
a = 7
b = 8
C = 45

# Конвертация угла в радианы
C = math.radians(C)

# Площадь
area = 0.5 * a * b * math.sin(C)
print("Площадь треугольника:", round(area, 2))

Площадь треугольника: 19.8


5. В прямоугольном треугольнике угол между гипотенузой и прилежащим катетом равен 30 градусов. Найдите длину противолежащего катета, если длина прилежащего катета равна 10.

Используйите библиотеку math. Формула: $$tan(θ) = {a\over b},$$

где:
- $θ$ — угол между прилежащим катетом и гипотенузой,
- $a$ — противолежащий катет,
- $b$ — прилежащий катет.


In [15]:
import math

angle_degrees = 30
b = 10

# Конвертация угла в радианы
angle_radians = math.radians(angle_degrees)

# Вычисление противолежащего катета
a = math.tan(angle_radians) * b
print("Длина противолежащего катета:", round(a, 2))

Длина противолежащего катета: 5.77


6. Даны два вектора $A = [1, 2, 3]$ и $B = [4, 5, 6]$. Найдите их скалярное произведение.

In [16]:
import numpy as np

# Векторы A и B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Скалярное произведение
dot_product = np.dot(A, B)
print("Скалярное произведение A и B:", dot_product)

Скалярное произведение A и B: 32


7. Создайте случайную матрицу размером 5x5 и вычислите ее обратную матрицу и определитель с использованием библиотеки numpy.

In [18]:
import numpy as np

A = np.random.rand(5, 5)

determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)

print(f"Определитель матрицы: {determinant}")
print("Обратная матрица:")
print(inverse)

Определитель матрицы: 0.21256769186835658
Обратная матрица:
[[ 0.85026321  0.69629316 -0.25762557 -1.32215823  0.33444859]
 [ 0.19630251 -1.15968788 -0.01032392  0.5014431   1.01747274]
 [-1.00034271  1.29264112 -0.36341262  0.04493343  0.65729165]
 [ 0.67252636 -0.27823948  0.3144033   0.91951947 -1.41309838]
 [-0.79743971 -0.20510499  1.61719393  0.74985961 -1.01017443]]


8. Даны две матрицы:
$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ и $B = \begin{bmatrix} 9 & 8 & 7 \\ 6 & 5 & 4 \\ 3 & 2 & 1 \end{bmatrix}$

Найдите их сумму.



In [26]:
import numpy as np

# Матрицы A и B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Сложение матриц
С = A + B
print("Сумма матриц A и B:\n", С)

Сумма матриц A и B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


9. Найдите ранг матрицы $B = \begin{bmatrix} 3 & 5 & 7 \\ 2 & 4 & 6 \\ 1 & 2 & 3 \end{bmatrix}$


In [29]:
import numpy as np

# Матрица B
B = np.array([
    [3, 5, 7],
    [2, 4, 6],
    [1, 2, 3]
])

# Вычисление ранга матрицы
rank_B = np.linalg.matrix_rank(B)
print("Ранг матрицы B:", rank_B)

Ранг матрицы B: 2


10. Даны два вектора  $A=[1,2,3]$  и  $B=[4,5,6]$. Найдите угол между ними в градусах.

In [31]:
import numpy as np

# Векторы A и B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# 1. Скалярное произведение
dot_product = np.dot(A, B)

# 2. Длины векторов
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

# 3. Вычисление косинуса угла
cos_theta = dot_product / (norm_A * norm_B)

# 4. Вычисление угла в радианах
theta_radians = np.arccos(cos_theta)

# 5. Конвертация угла в градусы
theta_degrees = np.degrees(theta_radians)
print("Угол между векторами в градусах:", round(theta_degrees, 2))


Угол между векторами в градусах: 12.93


# 11, 12 и 13 Задания со звездочкой по сложности!

11. Напишите программу, которая вычисляет собственные значения и собственные векторы случайной симметричной матрицы размером 1000x1000. Проверьте, что матрица действительно симметрична, и подтвердите, что все собственные значения являются действительными числами.

In [44]:
import numpy as np

# 1. Создаем случайную матрицу 1000x1000
n = 1000
m = 1000
A = np.random.rand(n, m)

# 2. Преобразуем её в симметричную матрицу
A_symm = (A + A.T)/2

# 3. Проверяем, что матрица симметрична
is_symmetric = np.allclose(A_symm, A_symm.T)
print(f"Матрица симметрична: {is_symmetric}")

# 4. Вычисляем собственные значения и собственные векторы
eigenvalues, eigenvectors = np.linalg.eig(A_symm)

# 5. Проверяем, что все собственные значения действительные
are_real = np.all(np.isreal(eigenvalues))
print(f"Все собственные значения действительные: {are_real}")

# Выводим результаты
print(f"Первое собственное значение: {eigenvalues[0]}")
print(f"Первый собственный вектор: {eigenvectors[:, 0]}")

Матрица симметрична: True
Все собственные значения действительные: True
Первое собственное значение: 499.9542079670885
Первый собственный вектор: [0.0311794  0.0323384  0.03130801 0.0313315  0.03156809 0.03187618
 0.03168161 0.03186382 0.03155129 0.03198342 0.03180762 0.0314442
 0.03119367 0.03215524 0.0317582  0.03125009 0.0312867  0.03180905
 0.03118303 0.03166863 0.03167484 0.03194859 0.03154825 0.03233118
 0.0312671  0.03138048 0.03223646 0.03081937 0.03134632 0.03113353
 0.03116436 0.0315711  0.03127    0.03170435 0.03188618 0.03124742
 0.03169262 0.03177615 0.03171826 0.03146048 0.03128036 0.0311884
 0.03224265 0.03176314 0.03197276 0.03259542 0.03125642 0.03078183
 0.03138083 0.03215684 0.03109292 0.0318737  0.03186101 0.03214792
 0.03195506 0.03167714 0.03145886 0.03219187 0.03125404 0.03070622
 0.0314506  0.03215138 0.0320146  0.03146838 0.03200576 0.03203945
 0.03170501 0.03138329 0.03168148 0.03196465 0.03129743 0.0311594
 0.03202038 0.03151531 0.03179421 0.03142496 0.032248

12. Расчет расстояния между двумя точками на сфере (формула гаверсинуса) Задача: Напишите функцию, которая вычисляет расстояние между двумя точками на поверхности Земли, заданными их широтой и долготой, используя формулу гаверсинуса.

Радиус Земли примите за 6371 км

Используйте:

`math.radians(), math.sin(), math.cos(), math.sqrt(), math.atan2()`

Формула Гаверсинуса выглядит так:
$$d = 2r \cdot \arcsin\left( \sqrt{ \sin^2\left( \dfrac{\Delta\phi}{2} \right) + \cos(\phi_1) \cdot \cos(\phi_2) \cdot \sin^2\left( \dfrac{\Delta\lambda}{2} \right) } \right)$$
**Где:**

- $ r $ — радиус Земли.

- $\phi_1, \phi_2$ — широты первой и второй точки в радианах.

- $\lambda_1, \lambda_2$ — долготы первой и второй точки в радианах.

- $\Delta\phi = \phi_2 - \phi_1$ — разница широт.

- $\Delta\lambda = \lambda_2 - \lambda_1$ — разница долгот.

In [ ]:
import math

def haversine(lat1, lon1, lat2, lon2):
    R = 6371

    lat1, lon1, lat2, lon2 = # ваш код

    return distance

# Координаты Москвы
lat1 = 55.7558
lon1 = 37.6173

# Координаты Нью-Йорка
lat2 = 40.7128
lon2 = -74.0060
print(haversine(lat1, lon1, lat2, lon2))

13. Для матрицы
$A = \begin{bmatrix} 6 & 2 \\ 2 & 3  \\  \end{bmatrix}$ найдите наибольшее собственное значение методом степенной итерации.

## Вспомогательный материал для решения задачи

### Метод степенной итерации

Метод степенной итерации используется для нахождения наибольшего по модулю собственного значения и соответствующего собственного вектора матрицы.

Основная идея метода заключается в том, что при многократном умножении случайного вектора на матрицу $ A $, доминирующее (наибольшее по модулю) собственное значение постепенно проявляется, так как собственные компоненты, соответствующие меньшим собственным значениям, затухают.

#### Формулировка метода степенной итерации:

1. Пусть $ A $ — квадратная матрица размера $ n \times n $.
2. Начните с произвольного ненулевого вектора $ b_0 $ (как правило, его компоненты можно задать случайно).
3. Повторяйте следующие шаги до достижения сходимости:

$$
b_{k+1} = \frac{A b_k}{||A b_k||}
$$

где:
- $ b_k $ — вектор на $ k $-ой итерации.
- $ ||A b_k|| $ — норма вектора, чаще всего используется евклидова норма.

4. После нескольких итераций вектор $ b_k $ будет приближаться к собственному вектору, соответствующему наибольшему по модулю собственному значению матрицы $ A $.

5. Найдите приближение к собственному значению с использованием вектора $ b_k $:

$$
\lambda_k = \frac{b_k^T A b_k}{b_k^T b_k}
$$

где:
- $ \lambda_k $ — приближение наибольшего собственного значения на $ k $-ой итерации.
- $ b_k^T $ — транспонированный вектор $ b_k $.

Этот метод работает хорошо для симметричных матриц и матриц с разными по величине собственными значениями.

In [ ]:
import numpy as np

# Матрица A
A = # ваш код

# Начальное приближение вектора
b = np.array([1, 1], dtype=float) # пояснение: если не преобразовать тип данных в float, то будет ошибка:
                                  # UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
tol = 1e-6
max_iter = 100

# Метод степенной итерации
for _ in range(max_iter):
    b_next = # ваш код

    if # ваш код:
        break
    b = b_next

# Собственное значение
largest_eigenvalue = # ваш код
print("Наибольшее собственное значение:", round(largest_eigenvalue,2))

14. Найдите радиус описанной окружности треугольника с длинами сторон $a = 3$, $b = 4$, $c = 5$.

Радиус описанной окружности треугольника $R$ можно найти по формуле:
$R = \frac{abc}{4A}$
где $a$, $b$, $c$ — длины сторон треугольника, а $A$ — его площадь.

In [ ]:
import math

# Длины сторон треугольника
a, b, c = 3, 4, 5

#ваш код
R = # ваш код
print("Радиус описанной окружности:", R)

15. Найдите длину кривой $\mathbf{r}(t) = (t^2, t^3, t)$ на интервале $[0, 1]$.

Длина кривой $\mathbf{r}(t) = (x(t), y(t), z(t))$ вычисляется по формуле:
$$ L = \int_a^b \sqrt{\left(\frac{dx}{dt}\right)^2 + \left(\frac{dy}{dt}\right)^2 + \left(\frac{dz}{dt}\right)^2} dt $$

In [48]:
import numpy as np
import math

# Производные компонентов кривой
def dxdt(t):
    return 2*t

def dydt(t):
    return 3*t**2

def dzdt(t):
    return 1

# Метод прямоугольников (/численого интегрирования)
a, b = 0, 1
n = 1000
dt = (b - a) / n
t = np.linspace(a, b, n+1)

# Вычисление длины кривой
length = 0
for i in range(n):
    length += math.sqrt(dxdt(t[i])**2 + dydt(t[i])**2 + dzdt(t[i])**2) * dt
print("Длина кривой:", round(length,2))

Длина кривой: 1.86


16. Найдите минимальное значение функции $f(x) = (x - 2)^2$ на отрезке $[0, 5]$ методом золотого сечения.

#### Формула метода золотого сечения:

Метод золотого сечения используется для минимизации унимодальной функции на заданном интервале. Этот метод позволяет последовательно сужать область поиска минимума до заданной точности.

Число золотого сечения $\varphi$ (phi) вычисляется по следующей формуле:
$\varphi = \frac{1 + \sqrt{5}}{2} \approx 1.618$

Процесс сужения интервала:
- Пусть начальный интервал поиска $[a, b]$.
- Определяются две новые точки внутри интервала:
  - $c = b - \frac{b - a}{\varphi}$
  - $d = a + \frac{b - a}{\varphi}$

- Вычисляются значения функции $f(c)$ и $f(d)$. Далее возможны два варианта:
  1. Если $f(c) < f(d)$, то новый интервал поиска: $[a, d]$.
  2. Если $f(c) \geq f(d)$, то новый интервал поиска: $[c, b]$.

Процесс продолжается до тех пор, пока длина интервала не станет меньше заданной точности $\epsilon$.

#### Пояснение:
Метод золотого сечения эффективно находит минимум функции за меньшее количество шагов по сравнению с методом перебора или равномерного деления интервала, так как использует пропорциональные отношения, характерные для числа золотого сечения.

In [51]:
# Функция для минимизации
def f(x):
    return (x - 2)**2

# Параметры метода золотого сечения
a, b = 0, 5
phi = (1 + math.sqrt(5)) / 2
tol = 1e-6

# Метод золотого сечения
while abs(a-b) >= tol:
    c = b - (b - a) / phi
    d = a + (b - a) / phi
    if f(c) < f(d):
        b = d
    else:
        a = c


# Минимальное значение функции
min_x = (a+b)/2
min_value = f(min_x)
print("Минимальное значение функции:", min_value, "при x =", min_x)

Минимальное значение функции: 1.5214922752069158e-14 при x = 2.000000123348785


17. Найдите угол между плоскостями $2x + 3y + 4z = 5$ и $x - 2y + z = 0$.

Угол между двумя векторами определяется по формуле:

$$
\cos(\theta) = \frac{\mathbf{n_1} \cdot \mathbf{n_2}}{|\mathbf{n_1}| |\mathbf{n_2}|},
$$

где:
- $\mathbf{n_1} \cdot \mathbf{n_2}$ — скалярное произведение нормальных векторов,
- $|\mathbf{n_1}|$ и $|\mathbf{n_2}|$ — длины нормальных векторов (их нормы).

In [ ]:
import numpy as np
import math

# Коэффициенты нормальных векторов
n1 = # ваш код
n2 = # ваш код

# Скалярное произведение и длины векторов
# ваш код

# Вычисление угла
cos_theta = # ваш код
theta = # ваш код

print("Угол между плоскостями:", theta, "градусов")

18. Найдите объем параллелепипеда, если его образуют векторы $\mathbf{a} = (11, 2, 3)$, $\mathbf{b} = (4, 5, 6)$ и $\mathbf{c} = (7, 8, 9)$.

Объем параллелепипеда, образованного тремя векторами $\mathbf{a}$, $\mathbf{b}$ и $\mathbf{c}$, вычисляется как абсолютное значение смешанного произведения: $$V=∣a⋅(b×c)∣$$

P.S. ошибки в векторах нет, в векторе а действительно стоит `11`, а не `1`

In [ ]:
import numpy as np

# Векторы
# ваш код

# Смешанное произведение
volume = # ваш код
print("Объем параллелепипеда:", volume)

19. Найдите координаты центра описанной окружности треугольника с вершинами $A(1, 2)$, $B(3, 4)$, $C(5, 1)$.

#### Формула для вычисления центра описанной окружности:

Центр описанной окружности для треугольника с вершинами $A(x_1, y_1)$, $B(x_2, y_2)$ и $C(x_3, y_3)$ можно найти с использованием пересечения серединных перпендикуляров к сторонам треугольника.

Для вычисления координат центра окружности $(x_o, y_o)$ используются следующие уравнения:

$$
x_o = \frac{ (x_1^2 + y_1^2)(y_2 - y_3) + (x_2^2 + y_2^2)(y_3 - y_1) + (x_3^2 + y_3^2)(y_1 - y_2) }{ 2 \cdot \Delta }
$$
$$
y_o = \frac{ (x_1^2 + y_1^2)(x_3 - x_2) + (x_2^2 + y_2^2)(x_1 - x_3) + (x_3^2 + y_3^2)(x_2 - x_1) }{ 2 \cdot \Delta }
$$

где $\Delta$ — определитель, равный удвоенной площади треугольника, вычисляемый как:

$
\Delta = \left| x_1(y_2 - y_3) + x_2(y_3 - y_1) + x_3(y_1 - y_2) \right|
$

#### Пояснение:

Координаты центра окружности определяются через пересечение серединных перпендикуляров к сторонам треугольника. Формулы учитывают координаты вершин треугольника и позволяют найти центр окружности.

In [ ]:
import numpy as np

# Координаты вершин треугольника
# ваш код

# Вычисление площади треугольника через определитель
def triangle_area(A, B, C):
    return # ваш код

# Определитель площади треугольника
Delta = triangle_area(A, B, C)

# Вычисление координат центра описанной окружности
x_o = # ваш код
y_o = # ваш код

print("Координаты центра описанной окружности:", (x_o, y_o))

20. Найдите площадь многоугольника с вершинами $P_1(1, 2)$, $P_2(4, 5)$, $P_3(7, 2)$, $P_4(4, 0)$.

Площадь многоугольника с вершинами $(x_1, y_1), (x_2, y_2), \dots, (x_n, y_n)$ вычисляется по формуле:

$$
A = \frac{1}{2} \left| \sum_{i=1}^{n-1} (x_i y_{i+1} - x_{i+1} y_i) + (x_n y_1 - x_1 y_n) \right|
$$

где $(x_1, y_1), (x_2, y_2), \dots, (x_n, y_n)$ — координаты вершин многоугольника, расположенных в порядке обхода.

In [ ]:
import numpy as np

# Координаты вершин многоугольника
vertices = # ваш код

# Вычисление площади
n = len(vertices)
area = 0
# ваш код

area = abs(area) / 2
print("Площадь многоугольника:", area)